css/detail.css
html/detail.html
javascript/detail.js

Could I get initial 👀 on this layout? @rfpoulos and @ponchieponcho ?

Detail page layout

---

html/contributeRoute.html
javascript/contributeRoute.js

hey guys, can now save new POIs as objects to database.  Also deleted my coffee app. . .  Pls approve! @ellenkramp @ponchieponcho

saving changes before pull request on master

---

javascript/listview.js

👀 please @ellenkramp @rfpoulos lemme know if I can merge. Note that the card isn't fully complete.

Display dynamic route card

---

css/detail.css
html/detail.html
index.html
javascript/contributeRoute.js
javascript/detail.js

@ellenkramp @ponchieponcho look before I do something to cause a merge conflict!

generates map based on given objects POIs

---

javascript/detail.js

@ellenkramp  @ponchieponcho  take a look pls!  I thought I was getting rid of global variables, but turns out that's not what they were.  I still think it is better to talk to the server in one go though.

refactor to remove individual promises to servers with one promise

---

css/login.css
html/login.html

@rfpoulos  and @ponchieponcho this is just setting up the framework, no javascript functionality added yet

setting up inputs and buttons

---

javascript/detail.js

@ellenkramp @ponchieponcho   Google doesn't allow navigation as part of their API - so I just open a window that repopulates the navigation instructions.

make a url request to google to start navigating in third party app

---

css/detail.css
html/detail.html
javascript/detail.js

Makes addPOIMarker more pure.  Minor styling on buttons on style page to go from column to row to give more room to the map. No new features, just cosmetic.
@ellenkramp @ponchieponcho   okay?

Minor refactor

---

javascript/detail.js

@ellenkramp  @ponchieponcho  Got distracted and made a function that gets the walkers location and puts a marker on the map that say "You are here."  Recommend cloning this branch and checking if it works.

puts user location on map

---

html/contributeRoute.html
javascript/contributeRoute.js
javascript/detail.js

@ellenkramp @ponchieponcho  Add goodies such as directional lines and distance.

Calculate distance

---

css/listview.css
javascript/listview.js
listview.html

👀 @ellenkramp @rfpoulos Got a single route card to pull all of the values from the server. I also refactored chunks into functions.
Things that are incomplete:
- Getting the distance from the user. Going to have to talk to yall who have touched the Google API.
- Blocked on getting the rating value out so I can do a function for generating the stars. Open to suggests.
- Getting length and time values. I think these should be generated during the creation process so we can pull them for both the list and detail view.
While I wait on some solutions for those, I'll be refactoring my code so it displays all of the routes on the server.

Route card with server info

---

javascript/listview.js

sorry small change that I need to push before going to another branch @ellenkramp @rfpoulos

three changed value names to match server data

---

css/listview.css
javascript/detail_and_listview.js
listview.html

@rfpoulos @ellenkramp Working list to detail view. Now getting detail view to list working.
Significant changes at the moment are:
detail.jss and listview.jss have been combined into detail_and_listview.js as to not screw up any work in detail
listview.html has had detail.html thrown into it to separate it
Apologies for the mess of code as I don't want to stop iterations on the OG detail page. Will get cleaned up tomorrow.

working list to detail view

---

html/contributeRoute.html
javascript/contributeRoute.js

The image uploader is in the form, it works and stores the image in our storage base. ☑️ I do need to work out how we can make our storage base talk to our detail/list view page to populate images though.
❓Also, when I try to submit the form, is spitting out an error that localRoute is undefined. I checked the top and saw where it was declared, but I can't find where in the code it was defined. @rfpoulos , do you think you could take a look?

added image uploader to contribute route form

---

listview.html

small bug, returns footer to listview.

returns footer

---

javascript/contributeRoute.js

I finally found a function to parse the filepath from the filename. I still need to figure out how to access the image so that it can be displayed on our detail/list view pages. @rfpoulos @ponchieponcho OK to merge?

added file name to walk stored object

---

css/listview.css

@ellenkramp @ponchieponcho  actually adds more styling to listview/details using flexbox.  Makes design more dynamic.  Recommend cloning and seeing the impact on your desktop.

Contribution style

---

html/contributeRoute.html
javascript/contributeRoute.js
listview.html

@ellenkramp @ponchieponcho  removes start location, doesn't seem to break list view or details page.  Also added function to check if use uploaded a picture.  If not, thumbnail set to null.  As a possible feature, if thumbnail is set to null, maybe we can default to our logo?

removes need for start location in form

---

css/contributeRoute.css
html/contributeRoute.html
javascript/contributeRoute.js

@ellenkramp @ponchieponcho adds image preview to page.  also does not create POI submit event listener until the initial walk object is initialized.

adds image preview to page

---

javascript/detail_and_listview.js
listview.html

@ellenkramp @rfpoulos working number but user location is only temp. Two solutions would be to attach user loc to user in database so it can update post list creation OR ask for location on login page/landing page then carry it into creating the list view.
Also added a library to the Google API call in the HTML

Distance from walker v2

---

javascript/detail_and_listview.js

I pulled the most recent master file after @ponchieponcho committed just now so this shouldn't override old changes anymore
@rfpoulos and @ponchieponcho  plz 👀

updated star function to display accurate rating

---

css/listview.css

@rfpoulos @ponchieponcho when a user hovers over a nav link, they will see the pointer hand now

added styling to a to show pointer on nav

---

css/listview.css
javascript/detail_and_listview.js
listview.html

@ellenkramp @rfpoulos Add section now in and...working? it seems
conflict is from those stupid arrows

ummm I made a iframe instead

---

javascript/detail_and_listview.js

@ellenkramp @ponchieponcho  Does as it says. Right now I just have it reorder the list as soon as the location is returns, but soon with buttons!  Easy to sort by any value from here (ratings, length, ect).

sorts based off of distance from walker

---

javascript/detail_and_listview.js

@ellenkramp does what it says.

adds query selector to add to make viewable

---

css/listview.css
index.html

once I added a div container for the listview div, I was able to get the bottom nav to stop overlappging on the list view page.

added div container for listview

---

css/listview.css
index.html
javascript/contributeRoute.js
javascript/detail_and_listview.js

@ellenkramp  all sortable now.

More sort fun

---

css/contributeRoute.css
html/contributeRoute.html

formatted form

---

javascript/contributeRoute.js

@rfpoulos default image should be good now

added a default image

---

css/listview.css

flex works on directory again

---

javascript/detail_and_listview.js

helps out refresh buf, stars no longer needs new call to DB
